kind: Deployment
apiVersion: apps/v1
metadata:
   name: mgelvoleo
spec:
   replicas: 2
   selector:      # tells the controller which pods to watch/belong to
    matchLabels:
     app: mgelvoleo
   template:
      metadata:
        labels:
          app: mgelvoleo
      spec:
       containers:
        - name: mgelvoleo
          image: mgelvoleo/cloud-cv-pipeline
          imagePullPolicy: Always
          ports:
          - containerPort: 80