kind: Service                             
apiVersion: v1
metadata:
  name: mgelvoleo
  labels:
    app: mgelvoleo
spec:
  ports:
    - port: 8443                            
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: mgelvoleo                    
  type: LoadBalancer                   